AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SPXFri67DTEDoubleCalendar

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  SPXFri67DTEDoubleCalendarFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: 'cron(50 15 ? * FRI *)'
            Name: SPXFri67DTEDoubleCalendarSchedule
            Description: SPXFri67DTEDoubleCalendar
      Environment:
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: /tastytrade/credentials
        - SSMParameterReadWritePolicy:
            ParameterName: /tastytrade/session_data

Outputs:
  SPXFri67DTEDoubleCalendarFunction:
    Description: "SPXFri67DTEDoubleCalendar Lambda Function ARN"
    Value: !GetAtt SPXFri67DTEDoubleCalendarFunction.Arn
  SPXFri67DTEDoubleCalendarFunctionIamRole:
    Description: "Implicit IAM Role created for SPXFri67DTEDoubleCalendar function"
    Value: !GetAtt SPXFri67DTEDoubleCalendarFunctionRole.Arn
