AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Bots

Resources:
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionSubstitutions:
        ProducerArn: !GetAtt Producer.Arn
        ConsumerArn: !GetAtt Consumer.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref Producer
        - LambdaInvokePolicy:
            FunctionName: !Ref Consumer
      DefinitionUri: statemachine.asl.json
  Consumer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/consumer/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
  Producer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/producer/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

Outputs:
  StateMachineArn:
    Description: State Machine ARN
    Value: !GetAtt StateMachine.Arn
  ConsumerArn:
    Description: Consumer ARN
    Value: !GetAtt Consumer.Arn
  ProducerArn:
    Description: Producer ARN
    Value: !GetAtt Producer.Arn
